---
# tasks file for web
    - name: 'Instalação de pacotes Aplicação Express'
      apt: 
        pkg: 
          - php7.0
          - php-pear
          - php7.0-curl
          - php7.0-gd
          - php7.0-intl
          - php7.0-xmlrpc
          - php7.0-mysql
          - apache2
          - python-mysqldb
          - wget
          - zip
          - curl
          - vim
        state: present
        update_cache: yes
    - name: 'Diretório do web server'
      file: 
        path: /srv/www
        state: directory
        owner: "{{ app_user}}"
        mode: '0755'
    - name: 'Download e extração do conteudo da aplicação'
      unarchive: 
        src: https://github.com/rogerramossilva/devops/raw/master/express.zip
        dest: /srv/www
        remote_src: yes
        validate_certs: no
    - name: 'Substituir Ip de conexão com BD no arquivo de backup.php'
      replace:
        path: /srv/www/express/backup.php
        regexp: '192\.168\.1\.20'
        replace: '172.17.177.102'   
    - name: 'Criando arquivo de configuração para virtual host da página express'
      template:
        src: "files/express.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
    - name: 'Criando Directory para controle das configurações Express'
      template:
        src: "files/direxpress.conf"
        dest: "/etc/apache2/conf-available/direxpress.conf"
    - name: 'Alterando arquivos /etc/hosts para resolução de nomes'
      template:
        src: "files/hostsintranet"
        dest: "/etc/hosts"
    - name: 'Habilitando site'
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: restart apache
    - name: 'Habilitando Configuração direxpress'
      shell: /usr/sbin/a2enconf direxpress.conf
      notify: restart apache
    - name: 'Habilitar modulos'
      apache2_module: 
        name: "{{ item }}"
        state: present
      loop: "{{ modsapache }}"  
      notify: restart apache
    - name: 'Permissão para usuario www-data'
      file:
        path: /srv/www/express
        state: directory
        recurse: yes
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
